### PR TITLE
Add React specimen to Markdown pages

### PR DESCRIPTION
**Pull request by herrstucki**
With this change, ReactSpecimen now can transform JS(X) on the fly using babel-standalone, so we can finally use it in Markdown documents (because they get compiled in the browser too)! It's excluded from the standalone build because including babel-standalone more than doubles the bundle size.

Additionally, Catalog now has a webpack loader which transforms Markdown documents directly to catalog page components (and they're hot-reloadable!). So now, writing documentation for react apps becomes as easy as writing it with Standalone Catalog! An example:

```js
import {render} from 'catalog';

render({
  title: 'My Components',
  pages: [
    {
      path: '/',
      title: 'Foo',
      // Import any components you want to render
      imports: {Foo: require('./components/Foo/index.js').default},
      // Import your Markdown documentation
      component: require('!!catalog/lib/loader!raw!./components/Foo/README.md')
    }
  ]
}, document.getElementById('app'));
```

Where `components/Foo/README.md` now looks like other Catalog-style documents:

    # Foo
    
    Blah

    ```react
    <Foo bar='baz' />
    ```

(One nice aspect is that this JSX code will look exactly the same in the ReactSpecimen's code block because it doesn't need to be inferred from an already rendered React element)

You can also put the loader config in your webpack config:

```js
{test: /\.md$/, include: 'src', loaders: ['catalog/lib/loader', 'raw']}
```

Some open questions:

- I'm not entirely happy with the `imports` and `component` terminology in the configuration (because `component` specifies the documentation) but it's backwards-compatible this way
- Maybe the loader could already precompile the whole markdown document?

### CODE REVIEW

**Comment by herrstucki** [comment]
Published as `catalog@next` :rocket:

**Comment by mhintz** [comment]
Nice! Is there a reason why normal `import` statements don't work, and we have to use `require`?

**Comment by herrstucki** [comment]
Nope, but import statements can't be inlined like this.

**Comment by wereHamster** [comment]
You should be able to move them to the top level, they are not in a closure.

**Comment by herrstucki** [comment]
Yes, you can also write

```js
import {render} from 'catalog';
import Foo from './components/Foo/index.js';
import FooDocs from '!!catalog/loader!raw!./components/Foo/README.md';

render({
  title: 'My Components',
  pages: [
    {
      path: '/',
      title: 'Foo',
      imports: {Foo},
      component: FooDocs
    }
  ]
}, document.getElementById('app'));
```

**Comment by mhintz** [comment]
Oh cool, this is what I was wondering about. Seemed like it could be an annoying thing to have to remember.

**Comment by naehrstoff** [comment]
Regarding the syntax for `imports`/`component`: here's another idea, maybe not the silver bullet either:

```
import {render} from 'catalog';
import Foo from './components/Foo/index.js';
import FooDocs from '!!catalog/lib/loader!raw!./components/Foo/README.md';

render({
  title: 'My Components',
  pages: [
    {
      path: '/',
      title: 'Foo',
      component: [FooDocs, {Foo}]
    }
  ]
}, document.getElementById('app'));
```

Another thing: I ran into problems several times when I changed a `src` from a Markdown doc to a React component. I always forgot to rename `src` to `component` and was stumped why it didn't work anymore. So if we're already thinking about the above syntax, it might be worthwile to try and find a solution where the config property stays the same in all cases. This also prevents the erroneous situation where both `src` and `component` properties are specified, for which it's undefined what should happen.

Could work like this:

```
pages: [
  { …, document: require('./p1.md') },
  { …, document: require('./p2.jsx') },
  { …, document: [require('./p3.jsx'), {Foo: require('components/Foo')}] },
]
```

Names could be: `component`, `renderer`, `document`, `doc`, `content`, `body`, …

**Comment by herrstucki** [comment]
Thanks for the feedback!

I don't think that `[FooDocs, {Foo}]` is a better syntax than using `imports`. It's much less obvious and error-prone. For example, what happens if you reverse the order or forget the object? E.g. `[{Foo}, FooDocs]`, `[FooDocs, Foo]` etc.

Also, you can specify the `imports` at the top level too, so you only have to do it once. It works exactly like `scripts` and `styles`.

I like the unified `src/component` property more, but I'm really not sure what a good name should be. `doc` and `document` feel a bit awkward when you think about it as `page.document`. `renderer` and `body` are too jargon-y. `content` seems to be the most neutral and appropriate for both use cases …

However, `src` still seems the most fitting for a resource which will be loaded (like ``), and `component` mirrors react-router's convention. With the support for loading Markdown documents directly, switching from one 'mode' to the other on different pages will become less likely anyway. That's why I'm reluctant to introduce this breaking change.

**Comment by herrstucki** [comment]
Oh, and by the way: when `src` and `component` are _both_ defined, a warning is logged. The same goes for when `pages` is specified together with `src` or `component` (because that's not possible too!).

I think we could do a little better about warning invalid configs though: a common error seems to be an `undefined` component, which results in a cryptic React warning. This can happen for instance when you forget to reference the default export like this `{..., component: require('components/Foo')}` instead of `{..., component: require('components/Foo').default}`.

**Comment by mhintz** [comment]
Yes! +1 for undefined component warning! And for more and earlier warnings in general

Mark

**Comment by herrstucki** [comment]
It's practically impossible to check for valid components because in the simplest case, they're just strings (e.g. `'div'` is technically a component) or functions (e.g. `const Foo = () => <div>Foo</div>`.

But I've changed the imports code in 585596d, so Catalog doesn't care anymore if it's a module with a `default` export or not. No warning needed for that :smile:

**Comment by herrstucki** [comment]
Merged into master, since most of the changes/discussion weren't related directly to this PR anymore.

Feel free to open a separate issue for the unified src/component config @naehrstoff if you feel that it's not been resolved.

**Pull request merged**
