### PR TITLE
Typesetting improvements

### LINKED ISSUE #444: Typography heading style conflicts and issues
I'm building a new Catalog using some of the specimens and am having an issue with how they're using various header elements in relation to a theme and global font sizes. 

One example is the Download specimen using an H2 and H3, which I have to re-style because my source styles for H1-H6 are much larger. The use of H2 and H3 are problematic and unsemantic and shouldn't be used in areas like these. 

There are many other areas where a heading tag is used but shouldn't (bottom navigation bar, etc). If just styling the containing div can be done, themeing would be much easier and not require many extra style overrides. The styles should be as agnostic as possible to allow for my own styles.

### PR DESCRIPTION
**Pull request by herrstucki**
Builds on @angelozehr's  and @mattfelten's PRs (thanks!) and fixes a few other things as well.

This also fixes #444.

I tried to address some common issues described in #347, although there's no "real" fix in this PR (and I don't really see one that's feasible at this point). 

Closes #442, closes #440

### CODE REVIEW

**Comment by mattfelten** [comment]
Do I have it right that from #440, we're opting to remove the active state completely from subnav items? Trying to trace the code changes. That seems fine to me, just want to make sure I understand how Catalog is changing.

**Comment by herrstucki** [comment]
@mattfelten no, nothing _should_ change fundamentally (If it does, that should be fixed). What I did is remove the distinct hover state on already active menu items and moved up the nested menu items by 8px, so the layout stays consistent. The `sidebarColorActive` theming option was not used anywhere in the code, that's why I removed it 😃

**Comment by herrstucki** [comment]
Your fix from #440 is also in here, that's why this PR closes it. Here's how it works now:

kapture 2018-08-23 at 9 08 01

**Comment by mattfelten** [comment]
Very cool!

**Pull request merged**
