### PR TITLE
React proptypes specimen

### PR DESCRIPTION
**Pull request by ajzozakiewicz**
# React PropTypes Specimen

Utilizes [react-docgen](https://github.com/reactjs/react-docgen) to parse the propTypes for a given component and display a table of properties, their values, and if they are required or not.

## Example

screen shot 2018-03-29 at 12 27 49 pm

### CODE REVIEW

**Comment by Zashy** [comment]
This would be cool to have.

**Comment by ajzozakiewicz** [comment]
@herrstucki any thoughts on this PR? Would greatly appreciate some review and conversation around this specimen.

**Comment by herrstucki** [comment]
@ajzozakiewicz Whoa, this is pretty cool 😎, thanks for proposing this! Something like this would be pretty nice to have.

Some high-level thoughts:

- It looks like you're parsing raw code in the browser. I haven't checked but this probably significantly adds to Catalog's bundle size (not sure how much but I estimate ~1MB like babel-standalone). I'd like to avoid this if possible.
- The Specimen could just use the _output_ of react-docgen, running docgen should be done elsewhere (e.g. manually, with a Babel plugin or webpack loader) – see https://github.com/interactivethings/catalog/issues/112#issuecomment-359812907
- Another reason for decoupling docgen from the specimen would be to let users plug in other docgen variants like https://github.com/styleguidist/react-docgen-typescript or https://github.com/vue-styleguidist/vue-docgen-api (not sure if their output is compatible though)

**Comment by ajzozakiewicz** [comment]
Thanks for the feedback @herrstucki! Extensibility is definitely something we should plan for.

Our original thoughts around including react-docgen in Catalog was to make it as easy as possible for consumers to use. Zero configuration needed to output the specimen.

I’m definitely open to making the specimen a docgen-specimen which just parses the different doc formats and outputs the same table but before we do, I wanted to communicate our thoughts on the original implementation.

Let me know what you think and we will update the specimen accordingly.

**Comment by jneuendorf** [comment]
@ajzozakiewicz Could you extract your changes into a separate repository? If you would use the [babel plugin](https://github.com/storybooks/babel-plugin-react-docgen) as mentioned in https://github.com/interactivethings/catalog/issues/112#issuecomment-359812907, I think all of the points @herrstucki made would be solved, wouldn't they?

**Comment by mattfelten** [comment]
Any updates on this?

**Pull request closed without merging**
