### PR TITLE
CLI

### PR DESCRIPTION
**Pull request by herrstucki**
### Instructions

- `make watch-cli`: compiles the CLI code
- Use `yarn link`, so you can link it from other projects and use the global commands
- `catalog start [source-dir]`: starts the Catalog server in dev mode in `[source-dir]` (`./catalog/` by default). If the directory doesn't exist, the CLI prompts you if it should create one.
- `catalog build [source-dir] -o [target-dir]`: creates a build in `[target-dir]` (`./catalog/build/` by default)
- Run `catalog [command] help` for more instructions
- Catalog will detect your app framework (Create React App, Next.js, generic) and use the appropriate webpack config, so everything should work out of the box.

### To Do

- [x] Copy static assets to build directory (CRA `/public` -> `[build-dir]`, Next: `/static` -> `[build-dir]/static`, …)
- [x] ~~Support for `catalog.config.js` which allows to customize webpack config, set the content base for static assets, public path for deployment etc.~~
- [x] CLI build step for publishing
- [x] Support for public path in build
- [x] Move docs to separate repo
- [x] Unbundle babel-standalone
- [ ] Add a cool CLI banner 😎 
- [x] Resolve the issue where builds take ~2min when Catalog's installed with npm@3 (everything's fine with yarn …). The culprit seems to be any kind of source maps.
- [x] Test on Node 4/npm 2
- [x] Don't prompt in a non-interactive environment
- [x] Add back InterpolateHtmlPlugin for PUBLIC_URL support (or find a good alternative)

### CODE REVIEW

**Comment by wereHamster** [comment]
Is the CLI supposed to work outside of a node package? I have a project which is just markdown documentation, there is no package.json. First problem is that detectFramework.js throws an exception. But even if I fix that, catalog depends on `catalog`, `react`, and `react-dom` being available in the current directory as a node module.

**Comment by herrstucki** [comment]
@wereHamster good question! Currently it's more built for the case where you have a CRA/Next-based app already set up. Initializing Catalog from scratch _could_ be interesting, although to make that work nicely you'd need to install it globally and then we could add an explicit `catalog init` command which modifies/creates `package.json` (e.g. like `next init` or `create-react-app` do). 

But in order to ship this, let's focus on fixing broken stuff. So if there's no `package.json` there, we could display a message with instructions to do `npm init` and `npm install react react-dom catalog --save`.

**Comment by herrstucki** [comment]
Alternatively, I think `catalog start` could also work in a project with no `package.json` out of the box if installed globally. The key thing to achieve that would be to make sure that the global `node_modules` is resolved correctly by webpack (already is?).

**Comment by wereHamster** [comment]
The precompiled cli tool depends on a npm package which is not included in the package.json dependencies, and that causes problems.

bin/catalog.js imports babel-polyfill, which imports core-js which, when compiled, expands to a bunch of require() statements. These require statements are tightly bound the the particular version of core-js that was using during compilation.

Our package.json specifies babel-polyfill ^6.23.0 (resolved to 6.23.0), whose dependency is core-js ^2.4.0 (resolved to 2.4.1), so the cli tool depends on core-js 2.4.1 at runtime.

When you add catalog@3.0.0-beta.4 to project (such as catalog-docs), yarn is helpful enough to hoist common dependencies to the top-level node_modules folder. However there catalog-docs depends on two distinct major versions of core-js (^1.0.0 and ^2.4.0), and yarn moves 1.0.0 to node_modules/core-js.

The effect is that catalog fails to run with "Error: Cannot find module 'core-js/modules/es7.string.pad-start'" as it can't see the correct version of core-js, it sees ^1.0.0 which doens't contain es7.string.pad-start.

**Comment by herrstucki** [comment]
@wereHamster I don't get that error, neither during dev nor build … yarn gives me this info:

```
> yarn list core-js
yarn list v0.21.3
├─ core-js@2.4.1
└─ fbjs@0.8.10
│  └─ core-js@1.2.7
```

`yarn why fbjs` thells me that only react and react-dom depend on it (and thus on core-js@1). Which yarn version are you using? Did you use any special settings (e.g. flat mode)?

**Comment by wereHamster** [comment]
> yarn list core-js                                                                                                                                                                           9:54
yarn list v0.19.1
├─ core-js@2.4.1
└─ fbjs@0.8.10
│  └─ core-js@1.2.7
✨  Done in 0.40s.

**Comment by wereHamster** [comment]
Sorry, that was the wrong output, here's the correct one:

› yarn list core-js

                                                9:59
yarn list v0.19.1
├─ babel-core@6.24.0
│  └─ core-js@2.4.1
├─ babel-generator@6.24.0
│  └─ core-js@2.4.1
├─ babel-helper-bindify-decorators@6.22.0
│  └─ core-js@2.4.1
├─ babel-helper-builder-binary-assignment-operator-visitor@6.22.0
│  └─ core-js@2.4.1
├─ babel-helper-builder-react-jsx@6.23.0
│  └─ core-js@2.4.1
├─ babel-helper-call-delegate@6.22.0
│  └─ core-js@2.4.1
├─ babel-helper-define-map@6.23.0
│  └─ core-js@2.4.1
├─ babel-helper-explode-assignable-expression@6.22.0
│  └─ core-js@2.4.1
├─ babel-helper-explode-class@6.22.0
│  └─ core-js@2.4.1
├─ babel-helper-function-name@6.23.0
│  └─ core-js@2.4.1
├─ babel-helper-get-function-arity@6.22.0
│  └─ core-js@2.4.1
├─ babel-helper-hoist-variables@6.22.0
│  └─ core-js@2.4.1
├─ babel-helper-optimise-call-expression@6.23.0
│  └─ core-js@2.4.1
├─ babel-helper-regex@6.22.0
│  └─ core-js@2.4.1
├─ babel-helper-remap-async-to-generator@6.22.0
│  └─ core-js@2.4.1
├─ babel-helper-replace-supers@6.23.0
│  └─ core-js@2.4.1
├─ babel-helpers@6.23.0
│  └─ core-js@2.4.1
├─ babel-messages@6.23.0
│  └─ core-js@2.4.1
├─ babel-plugin-check-es2015-constants@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-async-generator-functions@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-async-to-generator@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-class-properties@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-decorators@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-arrow-functions@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-block-scoped-functions@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-block-scoping@6.23.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-classes@6.23.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-computed-properties@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-destructuring@6.23.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-duplicate-keys@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-for-of@6.23.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-function-name@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-literals@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-modules-amd@6.24.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-modules-commonjs@6.24.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-modules-systemjs@6.23.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-modules-umd@6.24.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-object-super@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-parameters@6.23.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-shorthand-properties@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-spread@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-sticky-regex@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-template-literals@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-typeof-symbol@6.23.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-es2015-unicode-regex@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-exponentiation-operator@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-flow-strip-types@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-object-rest-spread@6.23.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-react-constant-elements@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-react-display-name@6.23.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-react-jsx-self@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-react-jsx-source@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-react-jsx@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-runtime@6.22.0
│  └─ core-js@2.4.1
├─ babel-plugin-transform-strict-mode@6.22.0
│  └─ core-js@2.4.1
├─ babel-polyfill@6.23.0
│  └─ core-js@2.4.1
├─ babel-preset-react-app@2.2.0
│  └─ core-js@2.4.1
├─ babel-preset-react@6.23.0
│  └─ core-js@2.4.1
├─ babel-register@6.24.0
│  └─ core-js@2.4.1
├─ babel-runtime@6.22.0
│  └─ core-js@2.4.1
├─ babel-template@6.23.0
│  └─ core-js@2.4.1
├─ babel-traverse@6.23.1
│  └─ core-js@2.4.1
├─ babel-types@6.23.0
│  └─ core-js@2.4.1
├─ core-js@1.2.7
└─ regenerator-transform@0.9.8
│  └─ core-js@2.4.1
✨  Done in 0.45s.

**Comment by herrstucki** [comment]
@wereHamster So it seems to be a yarn 0.19 bug? How about npm?

**Comment by wereHamster** [comment]
Tested with npm 4.0.5 (node 7.4.0), can't vouch for other versions. Though with npm 4.0.5 it also works only by chance because npm hoists the correct version (2.4.1) to the root and leaves core-js 1.2.7 private to the fbjs package. Any version of npm which doesn't deduplicate dependencies will not work.

**Comment by wereHamster** [comment]
The example does not work anymore. Its makefile depends on nodemon, and when I install that then it fails because bin/server does not exist anymore.

**Pull request merged**
