### PR TITLE
WIP Bundle with Rollup?

### PR DESCRIPTION
**Pull request by herrstucki**
Because Rollup supposedly generates smaller bundles than Webpack, I tried it out. So far no luck:

- The Webpacked `catalog.min.js` is 519KB
- Rollup's version is 589KB

Maybe I'm missing something in the Rollup config?

### CODE REVIEW

**Comment by herrstucki** [comment]
Switching to importing the minified js-yaml directly (aliased it in the Webpack config), brings the Rollup build down to 518KB!

I'm still getting some Babel helper related warnings like

```
The 'extends Babel helper is used more than once in your code. It's strongly recommended that you use the "external-helpers-2" plugin or the "es2015-rollup" preset. [...]
```

I'm using the `es2015-rollup` preset, so I'm not sure why I'm getting this warning …

**Comment by herrstucki** [comment]
After updating all dependencies, the warnings go away and the new results are:

- Webpack: 517kB
- Rollup: 516kB

So Rollup wins by ~1kB :sweat_smile: Not sure if it's worth to introduce another build tool and more dependencies to the mix (we still want Webpack at least for the hot-reloading development mode).

**Comment by herrstucki** [comment]
Okay, I made the classic React bundling mistake: I didn't replace `process.env.NODE_ENV` with `'production'`!

After that, the Rollup build goes down to 456kb! :boom:

**Comment by nolanlawson** [comment]
Nice! :tada:

**Pull request merged**
