### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by wiederkehr**
Added a new hint version for neutral, but important hints as well as removed the border-left on the blockquote making it a more natural lead content.

### CODE REVIEW

**Comment by wereHamster** [comment]
@herrstucki Any objections to this PR?

**Comment by herrstucki** [comment]
I'm not sure if we should change the default blockquote styles.

And if we start changing the hints, I think we could make some more improvements like better contrast between text and background (something which has been bothering me for a long time). I started some work on top of this PR once but never finished it … let me dig it up 🙂

**Comment by herrstucki** [comment]
Pushed my changes. It wasn't that much …

**Comment by herrstucki** [comment]
Okay, let's keep @wiederkehr's change. If someone complains, we bring the line back 😉 

One thing I'd still do though is improve text contrast in the hints.

**Pull request merged**
